export const WEATHER_GET = "WEATHER_GET";
export const FORECAST_GET = "FORECAST_GET";
export const AUTH_GET = "AUTH_GET";
export const COLOR_CHANGE = "COLOR_CHANGE";
export const SETTINGS_CHANGE_CITY = "SETTINGS_CHANGE_CITY";
